# Generated by Django 5.1.5 on 2025-01-24 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=50, verbose_name='name')),
                ('password', models.TextField(max_length=50, verbose_name='password')),
                ('status', models.IntegerField(default=1, verbose_name='status')),
                ('count', models.IntegerField(default=0, verbose_name='count')),
                ('lastLogin', models.DateField(verbose_name='lastLogin')),
                ('maxBet', models.IntegerField(default=0, verbose_name='maxBet')),
            ],
        ),
    ]
