# Generated by Django 5.1.5 on 2025-02-02 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_users_userclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='username',
            field=models.TextField(default='none', max_length=100, verbose_name='username'),
            preserve_default=False,
        ),
    ]
